### ISSUE TITLE
Video doesn't play smoothly

### ISSUE THREAD

**Issue by evelynkly** [crazoter/panplus#15]
**Describe the bug**
Everytime when I try to play w cideo, it doesn't play smoothly and jumps every seconds (with intercals of a few seconds or even a minute) even though I did not touch any key points. It has been occuring for 2 days now.

**To Reproduce**
Just play the video.

**Expected behavior**
Video is supposedly to play smootthly as per normal with no jumps.

**Desktop (please complete the following information):**
 I'm currently using chrome with windows 10.

**Additional context**

**Comment by crazoter** [comment]
Hello evelynkly, 

You could be referring to a feature. The extension also automatically detects silences and removes them from the webcast. 

In other words, if the extension works properly, whenever the professor is busy thinking of what to say, writing something on the screen or announces a break in the lecture, the extension will fast forward and skip these segments of the video to save you some time ("some" is an understatement considering it can save you ~20min per 2hr lecture), so you'll see the timestamp jump. This is expected behavior.

This feature sometimes glitches out when there is a problem with the audio of the webcast. If it does, go to the settings page, tick disable Silence Trimming and Save for the webcast.

If it trims too much (e.g. Prof is speaking but it skips so much to the point where you cannot understand him) you can tweak the settings to try and improve the accuracy of the feature (or just disable it entirely).

Do comment again if it continues to persist, but that should be the case.

**Comment by crazoter** [comment]
Since there has been no response I'll assume this issue is resolved.
